apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-api
  template:
    metadata:
      labels:
        app: php-api
    spec:
      containers:
        - name: php-api
          image: whatsapp-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql-service
            - name: REDIS_HOST
              value: redis-service
            - name: KAFKA_BROKER
              value: kafka-service:9092